### ISSUE TITLE
ServiceWorker?

### ISSUE THREAD

**Issue by requiredfield** [greatfire/redirect-when-blocked#5]
Does ServiceWorker buy us anything over AppCache?

Just came across http://jakearchibald.com/2014/offline-cookbook/ which says:

> When AppCache arrived on the scene it gave us a couple of patterns to make content work offline. If those were the patterns you needed, congratulations, you won the AppCache lottery (the jackpot remains unclaimed), but the rest of us were left huddled in a corner [rocking back & forth](http://alistapart.com/article/application-cache-is-a-douchebag).
>
> With ServiceWorker ([intro](http://www.html5rocks.com/en/tutorials/service-worker/introduction/)) we gave up trying to solve offline, and gave developers the moving parts to go solve it themselves. It gives you control over caching and how requests are handled. That means you get to create your own patterns. Let's take a look at a few possible patterns in isolation, but in practice you'll likely use many of them in tandem depending on URL & context.
>
> All code examples work today in Chrome 40 beta with the [cache polyfill](https://github.com/coonsta/cache-polyfill), unless otherwise noted. This stuff will land into the stable version January/February 2015 barring any emergencies, so it won't be long until millions of real users can benefit from this stuff.
>
> For a working demo of some of these patterns, see [Trained-to-thrill](https://jakearchibald.github.io/trained-to-thrill/), and [this video](https://www.youtube.com/watch?v=px-J9Ghvcx4) showing the performance impact.
>
> (cookbook contents follow)

If so, I guess we can keep an eye on https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorker_API#Browser_support for support in other browsers.

**Comment by requiredfield** [comment]
Tweet by [Addy Osmani](https://twitter.com/addyosmani) on [1/21/15, 18:00](https://twitter.com/addyosmani/status/558051510840356864)

> Chrome 40 is now stable. Over 750 million users will soon have Service Workers. Time to make our apps work offline :)

**Comment by greatfire-martin** [comment]
Very interesting. given that google is highly blocked, to what extent will users inside GFW update their version of Chrome?

**Comment by willscott** [comment]
According to http://caniuse.com/#feat=serviceworkers  there are currently 1% of worldwide users and 0.34% of Chinese users using browsers capable of service workers.

**Comment by requiredfield** [comment]
quoting https://twitter.com/FxSiteCompat/status/715908743351967744

> **Firefox Site Compat**: Application Cache API removal has been approved. It will be gone from @FirefoxNightly first. Use Service Workers. [bugzil.la/1237782](http://bugzil.la/1237782)
